# Generated by Django 3.0.3 on 2020-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
