# Generated by Django 3.0.4 on 2020-03-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Feedback',
        ),
    ]
