# Generated by Django 3.0.4 on 2020-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200331_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('username', models.TextField(verbose_name='Usename')),
                ('language', models.TextField(verbose_name='Selected language')),
                ('email', models.TextField(verbose_name='Email')),
            ],
        ),
    ]
