# Generated by Django 3.0.4 on 2020-03-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bot_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot_user',
            new_name='UserProfile',
        ),
    ]
