# Generated by Django 3.0.4 on 2020-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200331_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('channel_id', models.PositiveIntegerField(verbose_name='Channel ID')),
            ],
        ),
    ]
