# Generated by Django 3.0.4 on 2020-03-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='home.UserProfile', verbose_name='User Profile'),
            preserve_default=False,
        ),
    ]
