# Generated by Django 3.0.4 on 2020-03-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_postmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'Post Media', 'verbose_name_plural': 'Post Media'},
        ),
        migrations.CreateModel(
            name='PostLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(verbose_name='latitude')),
                ('longitude', models.TextField(verbose_name='longitude')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Location',
                'verbose_name_plural': 'Post Location',
            },
        ),
    ]
