# Generated by Django 3.0.3 on 2020-03-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('name', models.TextField(verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
