# Generated by Django 3.0.4 on 2020-03-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20200329_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
